#!/bin/sh
# Copyright (c) 2026 Job Snijders <job@bsd.nl>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

RELAY=miso.sobornost.net
CACHEDIR=/var/cache/rpki-client
CCRDIR=/var/db/rpki-client

FQDN=$(echo ${18} | sed 's|rsync://||' | xargs -r dirname)

case "${17}" in
        ".ta/ripe"|".ta/afrinic"|".ta/arin"|".ta/lacnic"|".ta/apnic")
                rsync $@
                exit $?
        ;;
        *)
esac

if [ -f "${CACHEDIR}/.rsync/${FQDN}-done" ]; then
        exit 0;
fi
if [ -f "${CACHEDIR}/.rsync/${FQDN}-lock" ]; then
        while true; do
                sleep 1
                if [ ! -f "${CACHEDIR}/.rsync/${FQDN}-lock" ]; then
                        exit 0;
                fi
                if [ -f "${CACHEDIR}/.rsync/${FQDN}-done" ]; then
                        exit 0;
                fi
        done
fi
touch "${CACHEDIR}/.rsync/${FQDN}-lock"


if [ -f "${CCRDIR}/rpki.ccr" ]; then
	rpkitouch -Cvd "${CACHEDIR}/.rsync" -H "${FQDN}" "${CCRDIR}/rpki.ccr"
fi
echo ${FQDN} XXX
pwd
exit 0
CURL_OPTS="-A erik15 -4 -e ${FQDN} -f --compressed -s -R"
