.\" $OpenBSD$
.\" Copyright (c) 2023,2025 Job Snijders <job@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt RPKITOUCH 8
.Os
.Sh NAME
.Nm rpkitouch
.Nd set file modification times to internal RPKI timestamps
.Sh SYNOPSIS
.Nm rpkitouch
.Op Fl n
.Fl c Ar ccr_file
.Nm rpkitouch
.Op Fl n
.Fl R Ar out_ccr
.Ar
.Nm rpkitouch
.Op Fl CnpVv
.Op Fl d Ar directory
.Ar
.Sh DESCRIPTION
The
.Nm
utility can inspect
.Em Canonical Cache Representation Pq CCR
objects, generate content-addressable filesystem hierarchies, and set the last
data modification time of
.Ar file
to the timestamp internal to the contained
.Em RPKI
object.
.Pp
.Nm
is useful for
.Em RPKI
Publication Point operators who serialize
.Em RPKI
objects from data sources lacking file modification times (such as
.Em RRDP )
to a disk hierachy for public consumption via
.Em RSYNC .
.Pp
.Em RPKI
Publication Point operators as well as
.Em Relying Parties
benefit from deterministic file modification times when synchronizing local
caches following data transfer protocol switches between
.Em RRDP
to
.Em RSYNC ,
because deterministic mod-times help minimize RP synchronisation load.
.Pp
For
.Em Autonomous System Provider Authorisation Pq ASPA ,
.Em Ghostbuster Records Pq GBR ,
.Em Manifests Pq MFT ,
.Em Route Origin Authorization Pq ROA ,
.Em Signed Prefix Lists Pq SPL ,
and
.Em Trust Anchor Key Pq TAK
objects the
.Em CMS signing-time
attribute is used as timestamp; for
.Em X.509
.Em CA
and
.Em EE
certificates the
.Em notBefore
is used as timestamp; for
.Em Certificate Revocation Lists Pq CRL
the
.Em thisUpdate
is used as timestamp.
.Pp
While the
.Nm
utility does not perform any cryptographic validation, the following sanity
checks are performed before setting the file modification time.
For
.Em CMS
files the self-signage and the presence of no more than one
.Vt CMS_SignerInfo
and one
.Em signing-time
attribute are confirmed.
.Em X.509
.Vt Certificate
and
.Em CRL
files must successfully decode into the applicable ASN.1 structure.
Files may not contain trailing data beyond the internal length markers.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl C
Compare and deduplicate ManifestRefs contained with the specified CCR
file(s).
If
.Fl d
is specified, generate and store Erik Synchronisation objects in
.Ar directory .
.It Fl c Ar ccr_file
Print the SHA-256 message digest and SIA field values of the ManifestRefs
contained within
.Ar ccr_file .
.It Fl d Ar directory
SHA-256 message digests are calculated for all objects and their content is
stored in
.Ar directory
using a content-addressable file naming scheme.
To improve performance, existing files are only overwritten if the size or
last modification timestamp differ.
.It Fl h
Display usage.
.It Fl n
No-op.
The file's modification time is computed but not set and no copies are made.
Can be combined with
.Fl d
and
.Fl v
to see what
.Nm
would change.
.It Fl p
Print the directory path derived from the SIA and the FileAndHashes contained
in a Manifest's payload, followed by the Manifest's own filename.
.It Fl R Ar out_ccr
Output a reduced CCR in
.Ar out_ccr
by removing all states except the ManifestState, and comparing and deduplicating
ManifestRefs in the specified CCR file(s).
.It Fl V
Display the version number and exit.
.It Fl v
Verbose operation.
.El
.Sh INSTALLATION
.Nm
runs on all operating systems with a libcrypto library based on
OpenSSL 1.1 or LibreSSL 3.6 or later.
.Sh EXIT STATUS
.Ex -std rpkitouch
.Sh EXAMPLES
Recursively set all data modification times of all files in a given directory
hierarchy to their respective
.Em RPKI
derived timestamps:
.Bd -literal -offset indent
$ cd /usr/share/rpki/publication/
$ find \&. -type f -exec rpkitouch {} \e+
.Ed
.Pp
Copy a signed object to
.Pa /tmp/a
with the Base64 encoded SHA-256 message digest as its target file name.
.Bd -literal -offset indent
$ rpkitouch -vd /tmp/test ./rpki.ripe.net/repository/ripe-ncc-ta.mft
rpkitouch: rpki.ripe.net/repository/ripe-ncc-ta.mft wtBCe8WjLELuoatWY9WSsfwpx9TvFqsLXh1jHQOdzCE (st:1756387926 sz:1786 d:1126859)
rpkitouch: named/rpki.ripe.net/repository/ripe-ncc-ta.mft (st:1756387926 sz:1786 d:1126859)

$ find /tmp/test
/tmp/test
/tmp/test/static
/tmp/test/static/wt
/tmp/test/static/wt/BC
/tmp/test/static/wt/BC/e8
/tmp/test/static/wt/BC/e8/wtBCe8WjLELuoatWY9WSsfwpx9TvFqsLXh1jHQOdzCE
/tmp/test/named
/tmp/test/named/rpki.ripe.net
/tmp/test/named/rpki.ripe.net/repository
/tmp/test/named/rpki.ripe.net/repository/ripe-ncc-ta.mft
.Ed
.Pp
An Erik relay worker job could be summarised as the following sequence of shell commands:
.Bd -literal -offset indent
#!/bin/sh
set -ev
while true; do
    rpki-client
    if [ -f /tmp/previous.ccr ]; then
        rpkitouch -c /tmp/previous.ccr > /tmp/previous.txt
    else
        echo > /tmp/previous.txt
    fi

    cp /var/db/rpki-client/rpki.ccr /tmp/current.ccr
    rpkitouch -c /tmp/current.ccr > /tmp/current.txt
    comm -1 -3 /tmp/previous.txt /tmp/current.txt | awk '{ print $NF }' > /tmp/new.txt
    cd /var/cache/rpki-client
    sort -R /tmp/new.txt | xargs rpkitouch -p | xargs rpkitouch -v -d /nfs
    rpkitouch -C -v -d /nfs /tmp/current.ccr
done
.Ed
.Sh STANDARDS
.Rs
.%T Internet X.509 Public Key Infrastructure Certificate and Certificate Revocation List (CRL) Profile
.%R RFC 5280
.Re
.Pp
.Rs
.%T Cryptographic Message Syntax (CMS)
.%R RFC 5652
.Re
.Pp
.Rs
.%T A Profile for X.509 PKIX Resource Certificates
.%R RFC 6487
.Re
.Pp
.Rs
.%T On the Use of the CMS Signing-Time Attribute in RPKI Signed Objects
.%R RFC 9589
.Re
.Pp
.Rs
.%T A Profile for RPKI Canonical Cache Representation
.%R https://datatracker.ietf.org/doc/html/draft-spaghetti-sidrops-rpki-ccr
.Re
.Pp
.Rs
.%T The Erik Synchronization Protocol for use with the RPKI
.%R https://datatracker.ietf.org/doc/html/draft-spaghetti-sidrops-rpki-erik-protocol
.%Re
.Sh AUTHORS
.An -nosplit
.An Job Snijders Aq Mt job@openbsd.org
