name: C

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install mandoc
      run: sudo apt install mandoc universal-ctags
    - name: make
      run: make
